import type { User, Schedule, FamilyGroup, Notification } from '@/types';

// ── 샘플 가족 구성원 ──
export const sampleUsers: User[] = [
  { id: 'u1', name: '김태호', email: 'taejo.kim@gmail.com', role: 'parent', familyGroupId: 'f1',
    spaceId: 'f1', avatar: '👨' },
  { id: 'u2', name: '김지수', email: 'jisu.kim@gmail.com',  role: 'parent', familyGroupId: 'f1',
    spaceId: 'f1', avatar: '👩' },
  { id: 'u3', name: '김민준', email: '',                    role: 'child',  familyGroupId: 'f1',
    spaceId: 'f1', avatar: '👦' },
  { id: 'u4', name: '김서연', email: '',                    role: 'child',  familyGroupId: 'f1',
    spaceId: 'f1', avatar: '👧' },
];

export const currentUser = sampleUsers[0];

export const sampleFamily: FamilyGroup = {
  id: 'f1',
  name: '김씨 가족',
  members: sampleUsers,
  inviteCode: 'GLEAUM-KIMF-2025',
  createdBy: 'u1',
  createdAt: new Date('2025-01-01'),
};

const today = new Date();
const addDays = (d: Date, n: number) => new Date(d.getFullYear(), d.getMonth(), d.getDate() + n);
const setTime = (d: Date, h: number, m = 0) => { const r = new Date(d); r.setHours(h, m, 0, 0); return r; };

// ── 샘플 일정 ──
export const sampleSchedules: Schedule[] = [
  {
    id: 's1',
    title: '민준이 생일파티 🎂',
    type: 'shared',
    startTime: setTime(addDays(today, 3), 15),
    endTime:   setTime(addDays(today, 3), 18),
    status: 'pending',
    participants: ['u1', 'u2', 'u3', 'u4'],
    location: { address: '서울 강남구 테헤란로 123', lat: 37.501, lng: 127.039 },
    reminder: 1440,
    repeat: 'none',
    memo: '케이크 주문 확인하기',
    familyGroupId: 'f1',
    spaceId: 'f1',
    createdBy: 'u2',
  },
  {
    id: 's2',
    title: '수학 학원',
    type: 'child',
    startTime: setTime(today, 16),
    endTime:   setTime(today, 18),
    status: 'in_progress',
    participants: ['u3'],
    location: { address: '서울 서초구 반포대로 456' },
    reminder: 30,
    repeat: 'weekly',
    familyGroupId: 'f1',
    spaceId: 'f1',
    createdBy: 'u1',
  },
  {
    id: 's3',
    title: '피아노 학원',
    type: 'child',
    startTime: setTime(today, 17),
    endTime:   setTime(today, 18),
    status: 'pending',
    participants: ['u4'],
    location: { address: '서울 서초구 방배로 789' },
    reminder: 30,
    repeat: 'weekly',
    familyGroupId: 'f1',
    spaceId: 'f1',
    createdBy: 'u1',
  },
  {
    id: 's4',
    title: '가족 외식 🍽️',
    type: 'shared',
    startTime: setTime(addDays(today, 5), 18),
    endTime:   setTime(addDays(today, 5), 20),
    status: 'pending',
    participants: ['u1', 'u2', 'u3', 'u4'],
    location: { address: '서울 종로구 인사동길 12' },
    reminder: 60,
    repeat: 'none',
    familyGroupId: 'f1',
    spaceId: 'f1',
    createdBy: 'u1',
  },
  {
    id: 's5',
    title: '치과 예약',
    type: 'personal',
    startTime: setTime(addDays(today, 7), 10),
    endTime:   setTime(addDays(today, 7), 11),
    status: 'pending',
    participants: ['u1'],
    reminder: 60,
    repeat: 'none',
    familyGroupId: 'f1',
    spaceId: 'f1',
    createdBy: 'u1',
  },
  {
    id: 's6',
    title: '영어 학원',
    type: 'child',
    startTime: setTime(addDays(today, -1), 15),
    endTime:   setTime(addDays(today, -1), 17),
    status: 'missed',
    participants: ['u3'],
    reminder: 30,
    repeat: 'weekly',
    familyGroupId: 'f1',
    spaceId: 'f1',
    createdBy: 'u1',
  },
  // 정기지출
  {
    id: 'e1',
    title: '민준 수학학원비',
    type: 'expense',
    startTime: setTime(new Date(today.getFullYear(), today.getMonth(), 25), 9),
    status: 'pending',
    participants: ['u1'],
    reminder: 4320,
    repeat: 'monthly',
    amount: 350000,
    expenseCategory: 'education',
    paymentMethod: 'auto',
    familyGroupId: 'f1',
    spaceId: 'f1',
    createdBy: 'u1',
  },
  {
    id: 'e2',
    title: '서연 피아노학원비',
    type: 'expense',
    startTime: setTime(new Date(today.getFullYear(), today.getMonth(), 25), 9),
    status: 'pending',
    participants: ['u1'],
    reminder: 4320,
    repeat: 'monthly',
    amount: 200000,
    expenseCategory: 'education',
    paymentMethod: 'auto',
    familyGroupId: 'f1',
    spaceId: 'f1',
    createdBy: 'u1',
  },
  {
    id: 'e3',
    title: '아파트 관리비',
    type: 'expense',
    startTime: setTime(new Date(today.getFullYear(), today.getMonth(), 20), 9),
    status: today.getDate() > 20 ? 'completed' : 'pending',
    participants: ['u1'],
    reminder: 4320,
    repeat: 'monthly',
    amount: 180000,
    expenseCategory: 'housing',
    paymentMethod: 'auto',
    familyGroupId: 'f1',
    spaceId: 'f1',
    createdBy: 'u1',
  },
  {
    id: 'e4',
    title: '전기요금',
    type: 'expense',
    startTime: setTime(new Date(today.getFullYear(), today.getMonth(), 15), 9),
    status: today.getDate() > 15 ? 'completed' : 'pending',
    participants: ['u1'],
    reminder: 1440,
    repeat: 'monthly',
    amount: 85000,
    expenseCategory: 'utility',
    paymentMethod: 'auto',
    familyGroupId: 'f1',
    spaceId: 'f1',
    createdBy: 'u1',
  },
  {
    id: 'e5',
    title: '넷플릭스',
    type: 'expense',
    startTime: setTime(new Date(today.getFullYear(), today.getMonth(), 1), 9),
    status: today.getDate() > 1 ? 'completed' : 'pending',
    participants: ['u1'],
    reminder: 1440,
    repeat: 'monthly',
    amount: 17000,
    expenseCategory: 'subscription',
    paymentMethod: 'card',
    familyGroupId: 'f1',
    spaceId: 'f1',
    createdBy: 'u1',
  },
];

// ── 샘플 알림 ──
export const sampleNotifications: Notification[] = [
  { id: 'n1', userId: 'u1', scheduleId: 's2', title: '수학 학원 시작', body: '김민준 수학 학원이 시작되었습니다.', type: 'reminder', read: false, createdAt: new Date(Date.now() - 1000 * 60 * 10) },
  { id: 'n2', userId: 'u1', scheduleId: 's6', title: '미완료 일정 알림', body: '영어 학원 일정이 완료되지 않았습니다.', type: 're_notify', read: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2) },
  { id: 'n3', userId: 'u1', scheduleId: 'e4', title: '전기요금 결제 예정', body: '내일 전기요금 85,000원이 자동이체 예정입니다.', type: 'reminder', read: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24) },
  { id: 'n4', userId: 'u1', scheduleId: 's1', title: '생일파티 D-3', body: '민준이 생일파티가 3일 후입니다.', type: 'reminder', read: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26) },
];
